# Generated by Django 5.2.17 on 2026-10-05 11:16

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("news", "0002_articleauthor_ordering"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeskAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g. Politics desk", max_length=80),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "style_guide",
                    models.TextField(
                        help_text="How this desk writes: priorities, tone, structure, what to avoid. Written as instructions to the writer."
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("claude-opus-5-5", "Claude Opus 5.5 (best quality)"),
                            (
                                "claude-sonnet-5-5",
                                "Claude Sonnet 5.5 (faster, cheaper)",
                            ),
                        ],
                        default="claude-opus-5-5",
                        max_length=40,
                    ),
                ),
                (
                    "effort",
                    models.CharField(
                        choices=[
                            ("medium", "Medium"),
                            ("high", "High (recommended)"),
                            ("xhigh", "Extra high"),
                        ],
                        default="high",
                        help_text="How hard the model thinks. Higher is slower and costs more.",
                        max_length=10,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "default_author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Byline used when the person commissioning a draft has no author profile",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="news.author",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="Drafts from this desk are filed in this section",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="desk_agents",
                        to="news.sectionpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "desk agent",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeskFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("news", "News"),
                            ("analysis", "Analysis"),
                            ("explainer", "Explainer"),
                        ],
                        help_text="Leave blank to apply to every article type",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField()),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to make the agent forget this note",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Added by an editor"),
                            ("review", "From a review comment"),
                        ],
                        default="manual",
                        editable=False,
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="news.articlepage",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "desk",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="newsdesk.deskagent",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="DraftRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_type",
                    models.CharField(
                        choices=[
                            ("news", "News"),
                            ("analysis", "Analysis"),
                            ("explainer", "Explainer"),
                        ],
                        default="news",
                        max_length=20,
                    ),
                ),
                (
                    "brief",
                    models.TextField(
                        help_text="What the story is, the angle you want, and anything the writer must cover"
                    ),
                ),
                (
                    "source_material",
                    models.TextField(
                        help_text="Paste the reporting the agent may use: notes, statements, report extracts, data, links. The agent is told to use only this material."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("writing", "Writing"),
                            ("done", "In review"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        editable=False,
                        max_length=10,
                    ),
                ),
                (
                    "editor_notes",
                    models.TextField(
                        blank=True,
                        editable=False,
                        help_text="What the agent says needs checking",
                    ),
                ),
                ("error", models.TextField(blank=True, editable=False)),
                (
                    "model_used",
                    models.CharField(blank=True, editable=False, max_length=60),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "cache_read_tokens",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="news.articlepage",
                    ),
                ),
                (
                    "byline",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to use your own author profile, or the desk's default author",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="news.author",
                    ),
                ),
                (
                    "desk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="newsdesk.deskagent",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "draft commission",
                "ordering": ["-created_at", "-pk"],
            },
        ),
    ]
