# Generated by Django 5.2.17 on 2026-10-05 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsdesk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftrequest",
            name="instructions",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="What the editor asked the agent to change",
            ),
        ),
        migrations.AddField(
            model_name="draftrequest",
            name="revision_of",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revisions",
                to="newsdesk.draftrequest",
            ),
        ),
    ]
