# Generated by Django 5.2.17 on 2026-10-07 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_articleauthor_ordering"),
        ("newsdesk", "0002_draft_revisions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="draftrequest",
            name="article_instructions",
            field=models.TextField(
                blank=True,
                help_text="Optional. Applies to this article only and is remembered on every revision (e.g. 'keep it under 600 words', 'no named companies'). Rules for every draft from this desk belong in the desk's memory instead.",
                verbose_name="special instructions for this article",
            ),
        ),
        migrations.CreateModel(
            name="ArticleNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("active", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("commission", "Special instructions"),
                            ("review", "Review comment"),
                            ("revision", "Revise with AI"),
                            ("manual", "Added by hand"),
                        ],
                        default="manual",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_notes",
                        to="news.articlepage",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "desk_rule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when an editor made this note a rule for the whole desk",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="newsdesk.deskfeedback",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
    ]
