# Generated by Django 5.2.17 on 2026-10-05 02:50

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
import wagtail.search.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        blank=True,
                        help_text="Optional strapline under the masthead",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SectionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="One or two sentences describing the section",
                    ),
                ),
                (
                    "show_on_homepage",
                    models.BooleanField(
                        default=True,
                        help_text="Show a block of this section's latest stories on the homepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "article_type",
                    models.CharField(
                        choices=[
                            ("news", "News"),
                            ("analysis", "Analysis"),
                            ("explainer", "Explainer"),
                            ("opinion", "Opinion"),
                            ("editorial", "Editorial"),
                        ],
                        default="news",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "standfirst",
                    models.TextField(
                        help_text="The summary line under the headline (max 300 characters)",
                        max_length=300,
                    ),
                ),
                ("hero_caption", models.CharField(blank=True, max_length=255)),
                ("hero_credit", models.CharField(blank=True, max_length=120)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("paragraph", 0),
                            ("heading", 1),
                            ("image", 4),
                            ("pullquote", 6),
                            ("key_points", 10),
                            ("qa", 13),
                            ("stat", 16),
                            ("callout", 17),
                            ("embed", 18),
                            ("table", 19),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link", "ol", "ul"],
                                    "template": "news/blocks/paragraph.html",
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "icon": "title",
                                    "template": "news/blocks/heading.html",
                                },
                            ),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 2), ("caption", 3), ("credit", 3)]],
                                {},
                            ),
                            5: ("wagtail.blocks.TextBlock", (), {}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 5), ("attribution", 3)]],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Key points"},
                            ),
                            8: ("wagtail.blocks.CharBlock", (), {"label": "Point"}),
                            9: ("wagtail.blocks.ListBlock", (8,), {}),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 7), ("points", 9)]],
                                {},
                            ),
                            11: ("wagtail.blocks.CharBlock", (), {}),
                            12: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "ol", "ul"]},
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 11), ("answer", 12)]],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "The number, e.g. ‘6.5%’ or ‘₹1.2 lakh crore’"
                                },
                            ),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "What the number measures"},
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [[("figure", 14), ("label", 15), ("source", 3)]],
                                {},
                            ),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 11), ("body", 12)]],
                                {},
                            ),
                            18: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"icon": "media", "template": "news/blocks/embed.html"},
                            ),
                            19: (
                                "wagtail.contrib.table_block.blocks.TableBlock",
                                (),
                                {"template": "news/blocks/table.html"},
                            ),
                        },
                    ),
                ),
                (
                    "sources",
                    wagtail.fields.StreamField(
                        [("source", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("publisher", 1),
                                        ("url", 2),
                                        ("note", 1),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Sources and references cited in the article",
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Shown as the publication date. Leave blank to use the first publish time.",
                        null=True,
                    ),
                ),
                (
                    "ai_assisted",
                    models.BooleanField(
                        default=False,
                        help_text="Tick if AI tools helped produce this article (see the AI policy)",
                        verbose_name="AI-assisted",
                    ),
                ),
                (
                    "ai_note",
                    models.CharField(
                        blank=True,
                        help_text="How AI was used, e.g. ‘AI summarised the 300-page report; figures checked by our desk.’",
                        max_length=300,
                        verbose_name="AI disclosure note",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "article",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ArticlePageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="news.articlepage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="articlepage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="news.ArticlePageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "role",
                    models.CharField(
                        blank=True, help_text="e.g. Political Editor", max_length=120
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "twitter",
                    models.CharField(
                        blank=True, help_text="Handle without the @", max_length=50
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Optional: the newsroom login for this author",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="author_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="HomeFeaturedArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="news.articlepage",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_articles",
                        to="news.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_authors",
                        to="news.articlepage",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_authors",
                        to="news.author",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
                "unique_together": {("page", "author")},
            },
        ),
    ]
