# Generated by Django 5.2.17 on 2026-10-05 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articleauthor",
            options={"ordering": ["sort_order", "pk"]},
        ),
    ]
