# Generated by Django 5.2.18 on 2026-10-08 18:26

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articleauthor_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.TextField(help_text='What was wrong and what we changed, e.g. ‘An earlier version said the bill passed in July. It passed in August.’')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='news.articlepage')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'abstract': False,
            },
        ),
    ]
