# Generated by Django 5.2.17 on 2026-10-05 02:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.TextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("paragraph", 0),
                            ("heading", 1),
                            ("image", 4),
                            ("pullquote", 6),
                            ("key_points", 10),
                            ("qa", 13),
                            ("stat", 16),
                            ("callout", 17),
                            ("embed", 18),
                            ("table", 19),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link", "ol", "ul"],
                                    "template": "news/blocks/paragraph.html",
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "icon": "title",
                                    "template": "news/blocks/heading.html",
                                },
                            ),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 2), ("caption", 3), ("credit", 3)]],
                                {},
                            ),
                            5: ("wagtail.blocks.TextBlock", (), {}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 5), ("attribution", 3)]],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Key points"},
                            ),
                            8: ("wagtail.blocks.CharBlock", (), {"label": "Point"}),
                            9: ("wagtail.blocks.ListBlock", (8,), {}),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 7), ("points", 9)]],
                                {},
                            ),
                            11: ("wagtail.blocks.CharBlock", (), {}),
                            12: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "ol", "ul"]},
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 11), ("answer", 12)]],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "The number, e.g. ‘6.5%’ or ‘₹1.2 lakh crore’"
                                },
                            ),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "What the number measures"},
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [[("figure", 14), ("label", 15), ("source", 3)]],
                                {},
                            ),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 11), ("body", 12)]],
                                {},
                            ),
                            18: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"icon": "media", "template": "news/blocks/embed.html"},
                            ),
                            19: (
                                "wagtail.contrib.table_block.blocks.TableBlock",
                                (),
                                {"template": "news/blocks/table.html"},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="The Ledger", max_length=80)),
                (
                    "tagline",
                    models.CharField(
                        default="News, analysis and argument from India", max_length=160
                    ),
                ),
                (
                    "publication_language",
                    models.CharField(
                        default="en",
                        help_text="ISO 639 code used in the Google News sitemap",
                        max_length=10,
                    ),
                ),
                (
                    "twitter_handle",
                    models.CharField(
                        blank=True, help_text="Without the @", max_length=50
                    ),
                ),
                (
                    "demo_notice",
                    models.BooleanField(
                        default=False,
                        help_text="Show a ‘demonstration content’ notice in the footer",
                    ),
                ),
                (
                    "default_share_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Used for Open Graph cards when a page has no image of its own",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "site settings",
            },
        ),
    ]
