# Generated by Django 5.2.18 on 2026-10-08 18:26

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceFormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='General enquiries', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='corrections_email',
            field=models.EmailField(blank=True, help_text='Where readers report errors; blank uses the contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='grievance_email',
            field=models.EmailField(blank=True, help_text='Complaints from the form are sent here', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='grievance_officer_designation',
            field=models.CharField(blank=True, default='Grievance Officer', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='grievance_officer_name',
            field=models.CharField(blank=True, help_text='Must live in India', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='grievance_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_name',
            field=models.CharField(blank=True, help_text='The company or LLP that publishes the site, as registered', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_email',
            field=models.EmailField(blank=True, help_text='Who answers questions about personal data; blank uses the grievance email', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registered_address',
            field=models.TextField(blank=True, help_text='Registered office: full postal address in India'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='self_regulatory_body',
            field=models.CharField(blank=True, help_text='The self-regulating body the publisher belongs to (IT Rules 2021, rule 12)', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='self_regulatory_body_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('heading', 1), ('image', 4), ('pullquote', 6), ('key_points', 10), ('qa', 13), ('stat', 16), ('callout', 17), ('embed', 18), ('table', 19), ('contact_details', 21), ('recent_corrections', 23)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'template': 'news/blocks/paragraph.html'}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'news/blocks/heading.html'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('credit', 3)]], {}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('quote', 5), ('attribution', 3)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Key points'}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Point'}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('title', 7), ('points', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 13: ('wagtail.blocks.StructBlock', [[('question', 11), ('answer', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'The number, e.g. ‘6.5%’ or ‘₹1.2 lakh crore’'}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'What the number measures'}), 16: ('wagtail.blocks.StructBlock', [[('figure', 14), ('label', 15), ('source', 3)]], {}), 17: ('wagtail.blocks.StructBlock', [[('title', 11), ('body', 12)]], {}), 18: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'template': 'news/blocks/embed.html'}), 19: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'template': 'news/blocks/table.html'}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('publisher', 'Publisher (legal name, address, email, phone)'), ('grievance', 'Grievance Officer'), ('privacy', 'Personal data questions'), ('corrections', 'Corrections')]}), 21: ('wagtail.blocks.StructBlock', [[('kind', 20)]], {}), 22: ('wagtail.blocks.IntegerBlock', (), {'default': 20, 'max_value': 100, 'min_value': 1}), 23: ('wagtail.blocks.StructBlock', [[('count', 22)]], {})}),
        ),
        migrations.CreateModel(
            name='GrievanceFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='core.grievanceformpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
