# Generated by Django 5.2.18 on 2026-10-10 13:38

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_publisher_details_grievance_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Manthan Reviews', max_length=80),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='Churning the news, distilling what matters', max_length=160),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('heading', 1), ('image', 4), ('pullquote', 6), ('key_points', 10), ('qa', 13), ('stat', 16), ('chart', 24), ('callout', 25), ('embed', 26), ('table', 27), ('contact_details', 29), ('recent_corrections', 31)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'template': 'news/blocks/paragraph.html'}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'news/blocks/heading.html'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('credit', 3)]], {}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('quote', 5), ('attribution', 3)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Key points'}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Point'}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('title', 7), ('points', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 13: ('wagtail.blocks.StructBlock', [[('question', 11), ('answer', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'The number, e.g. ‘6.5%’ or ‘₹1.2 lakh crore’'}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'What the number measures'}), 16: ('wagtail.blocks.StructBlock', [[('figure', 14), ('label', 15), ('source', 3)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'What the chart shows, e.g. ‘Women in the labour force, % of those aged 15+’'}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'Appended to each value, e.g. ‘%’ or ‘ GW’', 'required': False}), 19: ('wagtail.blocks.FloatBlock', (), {}), 20: ('wagtail.blocks.StructBlock', [[('label', 11), ('value', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'min_num': 1}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'Label of one bar to pick out in the accent colour', 'required': False}), 23: ('wagtail.blocks.CharBlock', (), {'help_text': 'Definitions, caveats or breaks in the series', 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('title', 17), ('unit', 18), ('bars', 21), ('highlight', 22), ('source', 3), ('note', 23)]], {}), 25: ('wagtail.blocks.StructBlock', [[('title', 11), ('body', 12)]], {}), 26: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'template': 'news/blocks/embed.html'}), 27: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'template': 'news/blocks/table.html'}), 28: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('publisher', 'Publisher (legal name, address, email, phone)'), ('grievance', 'Grievance Officer'), ('privacy', 'Personal data questions'), ('corrections', 'Corrections')]}), 29: ('wagtail.blocks.StructBlock', [[('kind', 28)]], {}), 30: ('wagtail.blocks.IntegerBlock', (), {'default': 20, 'max_value': 100, 'min_value': 1}), 31: ('wagtail.blocks.StructBlock', [[('count', 30)]], {})}),
        ),
    ]
